### ISSUE TITLE
Multi-layer(k-hop) implement

### ISSUE THREAD

**Issue by WangZesheng12** [yangbo1973/CM-HGNN#3]
Hello, excellent work!
According to your paper, CM-HGNN get best performance on Tmall and Diginetica when hop==2, but in your code, there isn't such implementation. Would you mind add it?
Because there are 2 ways to get there:
- 2layer(item-item, cate-cate, item-cate)
- 2layer(item-item), 2layer(cate-cate), 2layer(item-cate)
I don't know which way you choose to get your reported results in your paper(section 4.7.1 Table 4).

Looking forward to your reply!

**Comment by yangbo1973** [comment]
Thanks for your interest in our research. We use multi-layer GNN networks when learning item-category relation. For item-item and category-category relation, we use single-layer GNN network. 
> 2 layer (item-cate), 1 layer (item-item), 1 layer (cate-cate)

**Comment by WangZesheng12** [comment]
I got it. Thank you for your quick response!
